// flow-typed signature: 1892a3f57772a23dd80f65e5112fb4cd
// flow-typed version: <<STUB>>/react-native-permissions_v1.1.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-permissions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-native-permissions" {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-native-permissions/lib/permissions.android" {
    declare module.exports: any;
}

declare module "react-native-permissions/lib/permissions.ios" {
    declare module.exports: any;
}

// Filename aliases
declare module "react-native-permissions/index" {
    declare module.exports: $Exports<"react-native-permissions">;
}
declare module "react-native-permissions/index.js" {
    declare module.exports: $Exports<"react-native-permissions">;
}
declare module "react-native-permissions/lib/permissions.android.js" {
    declare module.exports: $Exports<"react-native-permissions/lib/permissions.android">;
}
declare module "react-native-permissions/lib/permissions.ios.js" {
    declare module.exports: $Exports<"react-native-permissions/lib/permissions.ios">;
}
