export const INIT_NOTIFICATION = "INIT/NOTIFICATION";
export const BRAZE_INIT_PUSH_NOTIFICATION = "BRAZE/INIT/PUSH_NOTIFICATION";
export const BRAZE_INIT_PUSH_STATUS = "BRAZE/INIT/PUSH_STATUS";
export const BRAZE_PUSH_NOTIFICATION_DATA = "BRAZE/PUSH_NOTIFICATION_DATA";
export const BRAZE_CLEAR_PUSH_NOTIFICATION_DATA = "BRAZE/CLEAR_PUSH_NOTIFICATION_DATA";
export const BRAZE_UPDATE_PUSH_NOTIFICATION_STATUS = "BRAZE/UPDATE_PUSH_NOTIFICATION_STATUS";

export const BRAZE_UPDATE_STATUS = "BRAZE/STATUS";
export const BRAZE_ENABLE = "BRAZE/ENABLE";
export const BRAZE_DISABLE = "BRAZE/DISABLE";
export const BRAZE_CHECK_PUSH_NOTIFICATION = "BRAZE/CHECK/PUSH_NOTIFICATION";

export const INIT_VIDEO_FULLSCREEN_ENTER = "VIDEO/FULLSCREEN/ENTER";
export const INIT_VIDEO_FULLSCREEN_EXIT = "VIDEO/FULLSCREEN/EXIT";
