export const PROFILE_NAVIGATION = "PROFILE/NAVIGATION";
export const PROFILE_TO_FOLLOWING = "PROFILE/TO/FOLLOWING";
export const PROFILE_TO_FOLLOWERS = "PROFILE/TO/FOLLOWERS";
export const PROFILE_TO_EDIT = "PROFILE/TO/EDIT";
export const PROFILE_TO_SETTINGS = "PROFILE/TO/SETTINGS";
export const PROFILE_TO_COMMENTS = "PROFILE/TO/COMMENTS";
export const PROFILE_TO_LIKES = "PROFILE/TO/LIKES";
export const PROFILE_TO_OTHER_PROFILE = "PROFILE/TO/OTHER_PROFILE";
export const PROFILE_TO_REPOST = "PROFILE/TO/REPOST";

export const PROFILE_CALL_REFRESH = "PROFILE/CALL/REFRESH";
export const PROFILE_CALL_LOADING_MORE = "PROFILE/CALL/LOADING_MORE";

export const PROFILE_CALL_FINISHED = "PROFILE/CALL/FINISHED";

export const PROFILE_NEW_FEEDS = "PROFILE/NEW_FEEDS";
