export const USER_LOG_IN = "USER/LOG_IN";
export const USER_LOG_IN_SUCCESS = "USER/LOG_IN/SUCCESS";
export const USER_LOG_IN_FAILURE = "USER/LOG_IN/FAILURE";
export const USER_VALID_TOKEN = "USER/VALID_TOKEN";
export const USER_INVALID_TOKEN = "USER/INVALID_TOKEN";

export const USER_SIGN_UP_SET_EMAIL = "USER/SIGN_UP/SET_EMAIL";
export const USER_SIGN_UP = "USER/SIGN_UP";
export const USER_SIGN_UP_SUCCESS = "USER/SIGN_UP/SUCCESS";
export const USER_SIGN_UP_FAILURE = "USER/SIGN_UP/FAILURE";

export const USER_SEND_RESET_EMAIL = "USER/SEND_RESET_EMAIL";

export const USER_RESET_PASSWORD = "USER/RESET_PASSWORD";
export const USER_RESET_PASSWORD_SUCCESS = "USER/RESET_PASSWORD/SUCCESS";
export const USER_RESET_PASSWORD_FAILURE = "USER/RESET_PASSWORD/FAILURE";

export const USER_UPDATE_PROFILE = "USER/UPDATE_PROFILE";
export const USER_UPDATE_PROFILE_INTERESTS = "USER/UPDATE_PROFILE_INTERESTS";
export const USER_UPDATE_PROFILE_SUCCESS = "USER/UPDATE_PROFILE/SUCCESS";
export const USER_UPDATE_PROFILE_FAILURE = "USER/UPDATE_PROFILE/FAILURE";

export const USER_FETCH_DETAILS = "USER/FETCH_DETAILS";
export const USER_FETCH_SUGGESTIONS = "USER/FETCH_SUGGESTIONS";
export const USER_FETCH_DETAILS_SUCCESS = "USER/FETCH_DETAILS/SUCCESS";
export const USER_FETCH_DETAILS_FAILURE = "USER/FETCH_DETAILS/FAILURE";

export const USER_EDIT_PASSWORD = "USER/EDIT_PASSWORD";

export const USER_DELETE_ACCOUNT = "USER/DELETE_ACCOUNT";

export const USER_LOG_OUT = "USER/LOG_OUT";

export const USER_FETCH_PROFILE = "USER/FETCH/PROFILE";
export const USER_FETCH_PROFILE_SUCCESS = "USER/FETCH/PROFILE_SUCCESS";

export const USER_UPDATE_ACCOUNT = "USER/UPDATE_ACCOUNT";
