export const DEEP_LINK_INIT = "DEEP_LINK/INIT";
export const DEEP_LINK_RESET_TOKEN = "DEEP_LINK/RESET_TOKEN";
export const DEEP_LINK_CLEAR_RESET_TOKEN = "DEEP_LINK/CLEAR_RESET_TOKEN";
export const DEEP_LINK_VERIFY_TOKEN = "DEEP_LINK/VERIFY_TOKEN";
export const DEEP_LINK_CLEAR_VERIFY_TOKEN = "DEEP_LINK/CLEAR_VERIFY_TOKEN";

export const DEEP_LINK_CHECK_AUTH = "DEEP_LINK/CHECK_AUTH";
export const DEEP_LINK_CHECK_MAIN = "DEEP_LINK/CHECK_MAIN";
export const DEEP_LINK_NEW_PASSWORD = "DEEP_LINK/NEW_PASSWORD";

export const DEEP_LINK_INFLUENCER = "DEEP_LINK/INFLUENCER";

export const DEEP_LINK_FIRST_OPEN = "DEEP_LINK/FIRST/OPEN";
