const MODULE_PREFIX = "GET_STREAM";

export const GET_STREAM_INIT_CLIENT: string = `${MODULE_PREFIX}/INIT_CLIENT`;
export const GET_STREAM_NOTIFICATIONS_REQUEST: string = `${MODULE_PREFIX}/NOTIFICATIONS/REQUEST`;
export const GET_STREAM_NOTIFICATIONS_SUCCESS: string = `${MODULE_PREFIX}/NOTIFICATIONS/SUCCESS`;
export const GET_STREAM_NOTIFICATION_SEEN: string = `${MODULE_PREFIX}/NOTIFICATION/SEEN`;
export const GET_STREAM_PROFILE_FEED_REQUEST: string = `${MODULE_PREFIX}/PROFILE_FEED/REQUEST`;
