export const TIMELINE_MOUNTED = "TIMELINE/MOUNTED";
export const TIMELINE_UNMOUNTED = "TIMELINE/UNMOUNTED";

export const TIMELINE_START = "TIMELINE/START";
export const TIMELINE_STOP = "TIMELINE/STOP";

export const TIMELINE_FEEDS_LOAD = "TIMELINE/FEEDS/LOAD";
export const TIMELINE_FEEDS_LOAD_FINISHED = "TIMELINE/FEEDS/LOAD/FINISHED";

export const TIMELINE_SUGGESTIONS_LOAD = "TIMELINE/SUGGESTIONS/LOAD";
export const TIMELINE_SUGGESTIONS_LOAD_FINISHED = "TIMELINE/SUGGESTIONS/LOAD/FINISHED";

export const TIMELINE_NEW_FEEDS_LOAD = "TIMELINE/NEW/FEEDS/LOAD";
export const TIMELINE_NEW_FEEDS_LOAD_FINISHED = "TIMELINE/NEW/FEEDS/LOAD/FINISHED";
