export const ACTIVITY_LOAD_COMMENTS = "ACTIVITY/LOAD_COMMENTS";
export const ACTIVITY_CREATE = "ACTIVITY/CREATE";
export const ACTIVITY_DELETE = "ACTIVITY/DELETE";
export const ACTIVITY_UPDATE = "ACTIVITY/UPDATE";
export const ACTIVITY_REPORT = "ACTIVITY/REPORT";
export const COMMENT_REPORT = "COMMENT/REPORT";

export const ACTIVITY_TOGGLE_LIKE = "ACTIVITY/TOGGLE_LIKE";
export const ACTIVITY_TOGGLE_LIKE_COMMENT = "ACTIVITY/TOGGLE_LIKE_COMMENT";
export const ACTIVITY_DELETE_COMMENT = "ACTIVITY/DELETE_COMMENT";
export const ACTIVITY_ADD_COMMENT = "ACTIVITY/ADD_COMMENT";
export const ACTIVITY_UPDATE_COMMENT = "ACTIVITY/UPDATE_COMMENT";

export const ACTIVITY_REPOST = "ACTIVITY/REPOST";
export const ACTIVITY_DELETE_REPOST = "ACTIVITY/DELETE_REPOST";
export const ACTIVITY_UPDATE_REPOST = "ACTIVITY/UPDATE_REPOST";
