export const EXPLORE_START = "EXPLORE/START";
export const EXPLORE_STOP = "EXPLORE/STOP";

export const EXPLORE_FEED_LOAD = "EXPLORE/FEED/LOAD";
export const EXPLORE_FEEDS_LOAD_FINISHED = "EXPLORE/FEEDS/LOAD/FINISHED";
